import "@/node_modules/react-modal-video/css/modal-video.css"
import 'swiper/css'
// import "swiper/css/navigation"
import "swiper/css/pagination"
import 'swiper/css/free-mode';
import '@/public/assets/css/style.css';
import { urbanist, mulish, dM_Sans } from '@/lib/font'
export const metadata = {
    title: 'Counsolve React Template',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en" className={`${mulish.variable} ${urbanist.variable} ${dM_Sans.variable}`}>
            <body>{children}</body>
        </html>
    )
}
