/**
 * BitString IT Services Pvt Ltd — Central Data Source
 * All business content lives here. Update this file to change site-wide content.
 */

export const company = {
    name: "BitString IT Services Pvt Ltd",
    tagline: "We Provide Solutions To Your IT Needs.",
    motto: "Connect :: Collaborate :: Deliver Values",
    description: "BitString IT Services Pvt Ltd is an ISO 27001 and ISO 9001 certified technology company providing Information Technology and Consulting Services. We leverage deep functional expertise and over 100 years of combined experience to help clients transform their businesses.",
    certifications: ["ISO 27001", "ISO 9001"],
    experience: "10+",
    email: "connect@bitstringit.com",
    offices: {
        india: {
            label: "Head Office (India)",
            address: "A-304, Nyati Empress, Vimamnagar, Pune, Maharashtra - 411014, BHARAT",
            phone: "(020) 69011184",
            mapsUrl: "https://maps.google.com/?q=A-304,+Nyati+Empress,+Vimamnagar,+Pune,+Maharashtra+411014",
        },
        usa: {
            label: "USA Office",
            address: "1268 Howard Ct, Carson City, NV 89703, USA",
            phone: "(949) 424-6646",
            mapsUrl: "https://maps.google.com/?q=1268+Howard+Ct,+Carson+City,+NV+89703",
        },
    },
    officeHours: "Mon - Sat: 9am to 6pm",
    clients: ["Schoolnet", "HADRON", "Successive Digital", "Infosys"],
    social: {
        linkedin: "https://www.linkedin.com/company/bitstringit",
        facebook: "#",
        youtube: "#",
    },
};

export const services = [
    {
        id: "itsm",
        slug: "itsm",
        title: "ITSM",
        fullTitle: "IT Service Management",
        icon: "flaticon-analytics",
        image: "assets/images/service/service-1.jpg",
        tagline: "Streamline IT operations with world-class service management.",
        shortDescription: "Optimize incident, problem, and change management with ServiceNow ITSM to maximize efficiency and minimize downtime.",
        longDescription: "BitString's ITSM consulting practice helps enterprises modernize their IT service delivery through ServiceNow. From initial assessment to full implementation, we configure and optimize every module to align with your specific business needs — delivering faster resolution times, better visibility, and measurable ROI.",
        features: [
            "Incident Management",
            "Problem Management",
            "Change & Release Management",
            "Service Catalog & Request Management",
            "Knowledge Management",
            "SLA Management & Reporting",
        ],
        benefits: [
            "Reduce mean time to resolve (MTTR)",
            "Improve end-user satisfaction",
            "Gain real-time visibility into IT operations",
            "Automate routine workflows and approvals",
        ],
        category: "ServiceNow",
    },
    {
        id: "itom",
        slug: "itom",
        title: "ITOM",
        fullTitle: "IT Operations Management",
        icon: "flaticon-global",
        image: "assets/images/service/service-2.jpg",
        tagline: "Full visibility across your entire digital infrastructure.",
        shortDescription: "Gain a real-time view of your IT infrastructure with Discovery, Service Mapping, and Event Management on ServiceNow.",
        longDescription: "Our ITOM practice ensures you always know the state of your IT environment. BitString configures ServiceNow's ITOM suite to auto-discover your infrastructure, build accurate service maps, and correlate events — reducing alert noise and enabling proactive operations before users are impacted.",
        features: [
            "Discovery & CMDB Population",
            "Service Mapping",
            "Event Management & AIOps",
            "Cloud Provisioning & Governance",
            "Orchestration",
            "Health Log Analytics",
        ],
        benefits: [
            "Eliminate shadow IT with automated discovery",
            "Reduce incidents with proactive monitoring",
            "Build a single source of truth for your CMDB",
            "Optimize cloud spend and governance",
        ],
        category: "ServiceNow",
    },
    {
        id: "itam",
        slug: "itam",
        title: "ITAM",
        fullTitle: "IT Asset Management",
        icon: "flaticon-money-bag",
        image: "assets/images/service/service-3.jpg",
        tagline: "Control your asset lifecycle from procurement to retirement.",
        shortDescription: "Track, manage, and optimize software and hardware assets throughout their complete lifecycle on ServiceNow.",
        longDescription: "BitString's ITAM implementation gives your organization a clear picture of every hardware and software asset you own — where it is, who uses it, what it costs, and when it needs to be replaced. We help you reduce audit risk, eliminate wasted spend, and maintain compliance at scale.",
        features: [
            "Hardware Asset Lifecycle Management",
            "Software Asset Management (SAM)",
            "License Compliance & Optimization",
            "Asset Inventory & Tracking",
            "Contract Management",
            "CMDB Integration",
        ],
        benefits: [
            "Eliminate software overspend and audit risk",
            "Automate asset procurement and offboarding",
            "Reduce hardware costs through optimization",
            "Achieve compliance with license agreements",
        ],
        category: "ServiceNow",
    },
    {
        id: "hrsd",
        slug: "hrsd",
        title: "HRSD",
        fullTitle: "HR Service Delivery",
        icon: "flaticon-team",
        image: "assets/images/service/service-4.jpg",
        tagline: "Transform the employee experience from day one.",
        shortDescription: "Deliver exceptional employee experiences with unified HR portals, lifecycle events, and case management on ServiceNow.",
        longDescription: "BitString helps HR teams move away from email chaos to a streamlined, self-service employee experience. We implement ServiceNow HRSD modules that give employees a single place to find answers, request services, and track the status of their requests — while giving HR teams visibility and efficiency at every step.",
        features: [
            "Employee Center (Self-Service Portal)",
            "HR Case & Knowledge Management",
            "Lifecycle Events (Onboarding/Offboarding)",
            "Candidate Hiring Integration",
            "Payroll & Benefits Service Delivery",
            "Employee Document Management",
        ],
        benefits: [
            "Reduce HR case resolution time by up to 50%",
            "Deliver consistent, personalized employee experiences",
            "Automate onboarding and offboarding workflows",
            "Free HR teams from repetitive tasks",
        ],
        category: "ServiceNow",
    },
    {
        id: "csm",
        slug: "csm",
        title: "CSM",
        fullTitle: "Customer Service Management",
        icon: "flaticon-customer",
        image: "assets/images/service/service-5.jpg",
        tagline: "Proactive customer service that resolves issues before they escalate.",
        shortDescription: "Deliver seamless, proactive customer service with self-service portals and intelligent case routing on ServiceNow CSM.",
        longDescription: "BitString's CSM practice helps organizations elevate customer satisfaction by connecting every department to the customer issue. We implement ServiceNow CSM to give your teams complete visibility into every case, automate escalations, and offer customers a self-service experience that resolves issues faster.",
        features: [
            "Case Management & Routing",
            "Customer Self-Service Portal",
            "Proactive Customer Service Operations",
            "Omni-Channel Integration",
            "Communities & Knowledge Base",
            "Field Service Management Integration",
        ],
        benefits: [
            "Increase customer satisfaction (CSAT) scores",
            "Reduce cost-per-case with self-service",
            "Connect front-office and back-office teams",
            "Enable proactive issue resolution",
        ],
        category: "ServiceNow",
    },
    {
        id: "grc",
        slug: "grc",
        title: "GRC",
        fullTitle: "Governance, Risk & Compliance",
        icon: "flaticon-shield",
        image: "assets/images/service/service-6.jpg",
        tagline: "Manage risk and stay audit-ready — at all times.",
        shortDescription: "Implement GRC frameworks on ServiceNow to manage regulatory risk, audit readiness, and security compliance in one place.",
        longDescription: "With an increasingly complex regulatory landscape, BitString helps you bring governance, risk, and compliance into one connected platform. We configure ServiceNow GRC to automate risk assessments, track controls, and generate audit-ready reports — so compliance becomes a business capability, not just a burden.",
        features: [
            "Risk Management & Assessment",
            "Policy & Compliance Management",
            "Audit Management",
            "Business Continuity Management",
            "Third-Party Risk Management",
            "Security Operations Integration",
        ],
        benefits: [
            "Reduce audit preparation time significantly",
            "Automate control testing and evidence collection",
            "Get a real-time view of your risk posture",
            "Meet regulatory requirements confidently",
        ],
        category: "ServiceNow",
    },
    {
        id: "cybersecurity",
        slug: "cybersecurity",
        title: "Cybersecurity",
        fullTitle: "Cybersecurity Services",
        icon: "flaticon-risk-management",
        image: "assets/images/service/service-7.jpg",
        tagline: "Protecting your digital assets in an evolving threat landscape.",
        shortDescription: "Expert cybersecurity strategy, assessments, and managed security solutions to protect your organization's digital ecosystem.",
        longDescription: "BitString's cybersecurity team provides organizations with the expertise to identify, assess, and mitigate security risks. From security architecture design to vulnerability assessments and compliance frameworks, we build resilient security postures that protect your data, systems, and reputation.",
        features: [
            "Security Assessment & Penetration Testing",
            "Security Architecture Design",
            "Identity & Access Management",
            "Threat Detection & Incident Response",
            "Cloud Security",
            "Compliance & Regulatory Advisory (ISO 27001, SOC 2)",
        ],
        benefits: [
            "Identify vulnerabilities before attackers do",
            "Build a defense-in-depth security architecture",
            "Achieve regulatory compliance with confidence",
            "Reduce incident response time and impact",
        ],
        category: "Technology Services",
    },
    {
        id: "devops-cloud",
        slug: "devops-cloud",
        title: "DevOps & Cloud",
        fullTitle: "DevOps & Cloud Services",
        icon: "flaticon-cloud",
        image: "assets/images/service/service-8.jpg",
        tagline: "Accelerate delivery and scale with modern cloud practices.",
        shortDescription: "Modernize your development lifecycle and infrastructure with DevOps best practices and cloud adoption strategies.",
        longDescription: "BitString helps organizations break down the wall between development and operations teams through proven DevOps methodologies and cloud-first strategies. We work with you to design CI/CD pipelines, containerize workloads, and migrate to cloud environments — enabling faster, more reliable software delivery.",
        features: [
            "CI/CD Pipeline Design & Implementation",
            "Cloud Migration & Architecture (AWS, Azure, GCP)",
            "Infrastructure as Code (IaC)",
            "Container Orchestration (Docker, Kubernetes)",
            "Monitoring & Observability",
            "Site Reliability Engineering (SRE)",
        ],
        benefits: [
            "Reduce time-to-market for new features",
            "Increase deployment frequency and reliability",
            "Lower infrastructure costs with cloud optimization",
            "Eliminate manual and error-prone processes",
        ],
        category: "Technology Services",
    },
];

export const training = {
    title: "Training & Career Programs",
    description: "BitString offers training programs designed to help IT professionals stay ahead in the rapidly evolving technology landscape — from ServiceNow fundamentals to advanced certifications.",
    benefits: [
        { title: "Expert Instructors", description: "Learn from industry professionals with years of hands-on ServiceNow and IT experience." },
        { title: "Hands-on Learning", description: "Practical exercises, real-world scenarios, and live platform access to apply what you learn." },
        { title: "Certification Prep", description: "Receive recognized certifications and guidance for official ServiceNow certification exams." },
        { title: "Career Support", description: "Job placement assistance and career guidance — we help you land the right role." },
    ],
};

export const faqs = [
    {
        question: "What ServiceNow modules does BitString implement?",
        answer: "BitString provides end-to-end implementation across ITSM, ITOM, ITAM, HRSD, CSM, SPM, and GRC. Our certified consultants cover the full ServiceNow ecosystem to ensure your platform delivers maximum value.",
    },
    {
        question: "Is BitString ISO certified?",
        answer: "Yes. BitString IT Services Pvt Ltd holds ISO 27001 certification (Information Security Management) and ISO 9001 certification (Quality Management System), reflecting our commitment to security and consistent service quality.",
    },
    {
        question: "Do you offer Talent Provisioning services?",
        answer: "Absolutely. Our Talent Provisioning service connects clients with certified, experienced IT professionals who have the precise skills and certifications required for their projects — from ServiceNow developers to cybersecurity specialists.",
    },
    {
        question: "Where are BitString's offices located?",
        answer: "Our India headquarters is at A-304, Nyati Empress, Vimamnagar, Pune, Maharashtra – 411014. We also operate a USA office at 1268 Howard Ct, Carson City, NV 89703. Contact us at connect@bitstringit.com.",
    },
    {
        question: "How does BitString approach a new project?",
        answer: "We follow a structured 3-phase approach: Discovery & Consultation (understanding your business), Solution Design (tailoring the right technology solution), and Implementation & Delivery (executing with certified experts and ongoing support).",
    },
    {
        question: "Do you provide post-implementation support?",
        answer: "Yes. We offer ongoing managed support and optimization services post-implementation to ensure your ServiceNow or technology platforms continue to perform at their best as your business evolves.",
    },
];
